pipeline {
    agent any

    environment {
        ECR_REPO = '286549082566.dkr.ecr.us-east-1.amazonaws.com/webchat-app/profile-service'
        DOCKER_REPO = "deepaksag/webchat-app"
        IMAGE_NAME = 'profile-service'
        IMAGE_TAG = "profile-v1.0.0"
        AWS_ACCESS_KEY_ID = credentials('awscreds')
        AWS_SECRET_ACCESS_KEY = credentials('awscreds')
        AWS_REGION = 'us-east-1'
    }

    stages {
        stage('Check Python') {
            steps {
                sh 'python3 --version'
                sh 'pip3 --version'
            }
        }
        
        stage('Checkout') {
            steps {
                git branch: 'spring', url: 'https://github.com/Coding4Deep/project-01.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('microservice-web-chat/profile-service') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('microservice-web-chat/profile-service') {
                    sh '''
                        . venv/bin/activate
                        pip install pytest-cov
                        python -m pytest test_main.py -v --cov=. --cov-report=xml --cov-report=html
                    '''
                }
            }
            post {
                always {
                    dir('microservice-web-chat/profile-service') {
                        publishTestResults testResultsPattern: 'test-results.xml'
                        publishCoverage adapters: [coberturaAdapter('coverage.xml')], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')
                        archiveArtifacts artifacts: 'htmlcov/*', allowEmptyArchive: true
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('microservice-web-chat/profile-service') {
                    withSonarQubeEnv('MySonarQube') {
                        sh "sonar-scanner"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('microservice-web-chat/profile-service') {
                    echo "Building Docker image..."
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                dir('microservice-web-chat/profile-service') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'docker-hub-credentials', 
                            usernameVariable: 'DOCKERHUB_USERNAME', 
                            passwordVariable: 'DOCKERHUB_PASSWORD'
                        )
                    ]) {
                        sh """
                            echo \$DOCKERHUB_PASSWORD | docker login -u \$DOCKERHUB_USERNAME --password-stdin
                            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_REPO}:${IMAGE_TAG}
                            docker push ${DOCKER_REPO}:${IMAGE_TAG}
                        """
                    }
                }       
            }
        }

        stage('Push Docker Image to AWS ECR') {
            steps {
                dir('microservice-web-chat/profile-service') {
                    withAWS(credentials: 'awscreds', region: "${AWS_REGION}") {
                        sh """
                            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 286549082566.dkr.ecr.us-east-1.amazonaws.com
                            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
                            docker push ${ECR_REPO}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            dir('microservice-web-chat/profile-service') {
               echo "Cleaning up Docker images..."
               sh "docker image prune -af || true"
               sh "rm -rf venv || true"
            }
        }
    }
}
