@Library('webchat-shared-library') _

buildPythonService([
    serviceName: 'profile-service',
    servicePath: 'microservice-web-chat/profile-service',
    imageTag: 'profile-v1.0.0',
    dockerRepo: 'deepaksag/webchat-app',
    ecrRepoName: 'webchat-app/profile-service',
    ecrAccountId: '286549082566',
    awsRegion: 'us-east-1',
    gitUrl: 'https://github.com/Coding4Deep/project-01.git',
    gitBranch: 'spring',
    runTests: true,
    enableSonar: true,
    pushToDockerHub: true,
    pushToECR: true
])
