pipeline {
    agent any

    environment {
        ECR_REPO = 'webchat-app/user-service'
        DOCKER_REPO ="deepaksag/webchat-app"
        IMAGE_NAME = 'user-service'
        IMAGE_TAG = "user-v1.0.0"
        AWS_ACCESS_KEY_ID = credentials('awscreds')
        AWS_SECRET_ACCESS_KEY = credentials('awscreds')
        AWS_REGION = 'us-east-1'
    }
    tools {
        maven 'Maven3.9.11' 
        jdk 'jdk17'
    }

    stages {

        stage('Check Java') {
            steps {
                sh 'java -version'
                sh 'echo $JAVA_HOME'
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'spring', url: 'https://github.com/Coding4Deep/project-01.git'
            }
        }

         stage('Run Unit Tests') {
            steps {
                dir('microservice-web-chat/user-service') {
                    sh 'mvn clean test'
                }
            }
            post {
                always {
                    dir('microservice-web-chat/user-service') {
                        junit '**/target/surefire-reports/*.xml' // Publish JUnit reports
                    }
                }
            }
        }
        stage('JaCoCo Coverage') {
            steps {
                dir('microservice-web-chat/user-service') {
                    sh 'mvn jacoco:report'
                    archiveArtifacts artifacts: 'target/site/jacoco/*', allowEmptyArchive: true
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('microservice-web-chat/user-service') {
                    withSonarQubeEnv('MySonarQube') {
                        sh "mvn sonar:sonar"
                    }
                    // timeout(time: 5, unit: 'MINUTES') {
                    //     waitForQualityGate abortPipeline: true
                    // }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('microservice-web-chat/user-service') {
                    echo "Building Docker image..."
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }
        stage('Trivy Scan') {
            steps {
                script {
                    def imageName = "${IMAGE_NAME}:${IMAGE_TAG}"
                    sh """
                    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest --severity CRITICAL,HIGH image $imageName
                    """
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                sh """
                    echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_REPO}:${IMAGE_TAG}
                    docker push ${DOCKER_REPO}:${IMAGE_TAG}
                """
            }
        }

        stage('Push Docker Image to AWS ECR') {
            steps {
                echo "Pushing Docker image to AWS ECR..."
                withCredentials([[ credentialsId: "${AWS_CREDENTIALS}"]]) {
                    sh """
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
                        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
                        docker push ${ECR_REPO}:${IMAGE_TAG}
                    """
                }
            }
        }
    }

    post {
        always {
            dir('microservice-web-chat/user-service') {
               echo "Cleaning up Docker images..."
               sh " docker image prune -af|| true"
            }
        }
    }
}
