pipeline {
    agent any

    environment {
        // Docker registry credentials IDs stored in Jenkins
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
        AWS_CREDENTIALS = 'aws-creds'
        ECR_REPO = '123456789012.dkr.ecr.us-east-1.amazonaws.com/web-chat-user-service'
        IMAGE_NAME = 'web-chat-user-service'
        IMAGE_TAG = "v1.0.${BUILD_NUMBER}"
    }
    tools {
        maven 'Maven3.9.11' 
        jdk 'jdk17'
    }

    stages {

        stage('Check Java') {
            steps {
                sh 'java -version'
                sh 'echo $JAVA_HOME'
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'spring', url: 'https://github.com/Coding4Deep/project-01.git'
            }
        }

         stage('Run Unit Tests') {
            steps {
                dir('microservice-web-chat/user-service') {
                    sh 'mvn clean test'
                }
            }
            post {
                always {
                    dir('microservice-web-chat/user-service') {
                        junit '**/target/surefire-reports/*.xml' // Publish JUnit reports
                    }
                }
            }
        }
        stage('JaCoCo Coverage') {
            steps {
                dir('microservice-web-chat/user-service') {
                    sh 'mvn jacoco:report'
                    archiveArtifacts artifacts: 'target/site/jacoco/*', allowEmptyArchive: true
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('microservice-web-chat/user-service') {
                    withSonarQubeEnv('MySonarQube') {
                        sh "mvn sonar:sonar"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('microservice-web-chat/user-service') {
                    echo "Building Docker image..."
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

    //     stage('Push Docker Image to AWS ECR') {
    //         steps {
    //             echo "Pushing Docker image to AWS ECR..."
    //             withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: "${AWS_CREDENTIALS}"]]) {
    //                 sh """
    //                     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REPO}
    //                     docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
    //                     docker push ${ECR_REPO}:${IMAGE_TAG}
    //                 """
    //             }
    //         }
    //     }

    //     stage('Push Docker Image to Docker Hub') {
    //         steps {
    //             echo "Pushing Docker image to Docker Hub..."
    //             withDockerRegistry(credentialsId: "${DOCKERHUB_CREDENTIALS}", url: '') {
    //                 sh """
    //                     docker tag ${IMAGE_NAME}:${IMAGE_TAG} your-dockerhub-username/${IMAGE_NAME}:${IMAGE_TAG}
    //                     docker push your-dockerhub-username/${IMAGE_NAME}:${IMAGE_TAG}
    //                 """
    //             }
    //         }
    //     }
    }

    post {
        always {
            dir('microservice-web-chat/user-service') {
               echo "Cleaning up Docker images..."
               sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
            }
        }
    }
}
