@Library('webchat-shared-library') _

buildFrontend([
    serviceName: 'frontend',
    servicePath: 'microservice-web-chat/frontend',
    imageTag: 'frontend-v1.0.0',
    dockerRepo: 'deepaksag/webchat-app',
    ecrRepoName: 'webchat-app/frontend',
    ecrAccountId: '286549082566',
    awsRegion: 'us-east-1',
    gitUrl: 'https://github.com/Coding4Deep/project-01.git',
    gitBranch: 'spring',
    nodeVersion: 'NodeJS-18',
    runTests: true,
    enableSonar: true,
    pushToDockerHub: true,
    pushToECR: true
])
