pipeline {
    agent any

    environment {
        ECR_REPO = '286549082566.dkr.ecr.us-east-1.amazonaws.com/webchat-app/frontend'
        DOCKER_REPO = "deepaksag/webchat-app"
        IMAGE_NAME = 'frontend'
        IMAGE_TAG = "frontend-v1.0.0"
        AWS_ACCESS_KEY_ID = credentials('awscreds')
        AWS_SECRET_ACCESS_KEY = credentials('awscreds')
        AWS_REGION = 'us-east-1'
    }
    
    tools {
        nodejs 'NodeJS-18'
    }

    stages {
        stage('Check Node') {
            steps {
                sh 'node --version'
                sh 'npm --version'
            }
        }
        
        stage('Checkout') {
            steps {
                git branch: 'spring', url: 'https://github.com/Coding4Deep/project-01.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('microservice-web-chat/frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('microservice-web-chat/frontend') {
                    script {
                        try {
                            sh 'CI=true npm test -- --coverage --watchAll=false --passWithNoTests'
                        } catch (Exception e) {
                            echo "Tests failed but continuing: ${e.getMessage()}"
                            currentBuild.result = 'UNSTABLE'
                        }
                    }
                }
            }
            post {
                always {
                    dir('microservice-web-chat/frontend') {
                        echo 'Tests completed'
                        archiveArtifacts artifacts: 'coverage/**/*', allowEmptyArchive: true
                    }
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('microservice-web-chat/frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('microservice-web-chat/frontend') {
                    echo "Building Docker image..."
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                dir('microservice-web-chat/frontend') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'docker-hub-credentials', 
                            usernameVariable: 'DOCKERHUB_USERNAME', 
                            passwordVariable: 'DOCKERHUB_PASSWORD'
                        )
                    ]) {
                        sh """
                            echo \$DOCKERHUB_PASSWORD | docker login -u \$DOCKERHUB_USERNAME --password-stdin
                            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_REPO}:${IMAGE_TAG}
                            docker push ${DOCKER_REPO}:${IMAGE_TAG}
                        """
                    }
                }       
            }
        }

        stage('Push Docker Image to AWS ECR') {
            steps {
                dir('microservice-web-chat/frontend') {
                    withAWS(credentials: 'awscreds', region: "${AWS_REGION}") {
                        sh """
                            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 286549082566.dkr.ecr.us-east-1.amazonaws.com
                            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
                            docker push ${ECR_REPO}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            dir('microservice-web-chat/frontend') {
               echo "Cleaning up Docker images..."
               sh "docker image prune -af || true"
            }
        }
    }
}
