apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yml
- configmap.yml
- postgres-statefulset.yml
- postgres-service.yml
- deployment.yml
- service.yml
- hpa.yml

namespace: user-service

commonLabels:
  project: webchat
  component: user-service
