apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: user-service
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 40
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: userdb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-db-username
              key: postgre-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-db-secret
              key: postgre-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "1000m"
            memory: "1200Mi"
          limits:
            cpu: "5500m"
            memory: "2Gi"
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 5Gi


---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: user-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  clusterIP: None