---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart sonarqube
  ansible.builtin.systemd:
    name: sonarqube
    state: restarted
    enabled: yes

- name: Enable and start Nexus
  ansible.builtin.systemd:
    name: nexus
    enabled: yes
    state: restarted