@Library('webchat-shared-library') _

buildMicroservice([
    serviceName: 'monitoring-service',
    servicePath: 'microservice-web-chat/monitoring-service',
    imageTag: 'monitoring-v1.0.0',
    dockerRepo: 'deepaksag/webchat-app',
    ecrRepoName: 'webchat-app/monitoring-service',
    ecrAccountId: '286549082566',
    awsRegion: 'us-east-1',
    gitUrl: 'https://github.com/Coding4Deep/project-01.git',
    gitBranch: 'spring',
    enableSonar: true,
    pushToDockerHub: true,
    pushToECR: true
])
