@Library('webchat-shared-library') _

buildService([
    serviceName: 'posts-service',
    servicePath: 'microservice-web-chat/posts-service',
    techStack: 'go',
    goVersion: 'Go-1.21',
    imageTag: 'posts-v1.0.0',
    dockerRepo: 'deepaksag/webchat-app',
    ecrRepoName: 'webchat-app/posts-service',
    ecrAccountId: '286549082566',
    awsRegion: 'us-east-1',
    gitUrl: 'https://github.com/Coding4Deep/project-01.git',
    gitBranch: 'spring',
    enableSonar: true,
    pushToDockerHub: true,
    pushToECR: true
])
