---
- name: Install and configure Jenkins
  hosts: 
    - jen_master_02
  become: yes
  roles:
    - Roles/jenkins
  tags:
    - jenkins_setup

- name: Change hostname for Jenkins master 02
  hosts:
    - jen_master_02
  become: yes
  tasks:
    - name: Set hostname for jen_master_02
      ansible.builtin.hostname:
        name: master-02
  tags:
  - jen-hostname



    